<a href="https://colab.research.google.com/github/dharanishree-p/FDS_RECORD/blob/main/11_Ex_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("employee - Sheet1 (1).csv")

In [2]:
df.head()

   EmpId                  Name  Salary
0      1     SREE VARSSINI K S    5000
1      2           SREEMATHI B    6000
2      3               SREYA G    7000
3      4  SREYASKARI MULLAPUDI    5000
4      5         SRI AKASH U G    8000

In [3]:
df.tail()

   EmpId                   Name  Salary
2      3                SREYA G    7000
3      4   SREYASKARI MULLAPUDI    5000
4      5          SRI AKASH U G    8000
5      6  SRI HARSHAVARDHANAN R    3000
6      7  SRI HARSHAVARDHANAN R    6000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EmpId   7 non-null      int64
 1   Name    7 non-null      object
 2   Salary  7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [5]:
df.Salary

0    5000
1    6000
2    7000
3    5000
4    8000
5    3000
6    6000
Name: Salary, dtype: int64

In [6]:
type(df.Salary)

pandas.core.series.Series

In [7]:
df.Salary.mean()

np.float64(5714.285714285715)

In [8]:
df.Salary.median()

6000.0

In [9]:

df.Salary.mode()

0    5000
1    6000
Name: Salary, dtype: int64

In [10]:
df.Salary.var()

2571428.5714285714

In [11]:

df.Salary.std()

1603.5674514745463

In [12]:
df.describe()

          EmpId       Salary
count  7.000000     7.000000
mean   4.000000  5714.285714
std    2.160247  1603.567451
min    1.000000  3000.000000
25%    2.500000  5000.000000
50%    4.000000  6000.000000
75%    5.500000  6500.000000
max    7.000000  8000.000000

In [13]:
df.describe(include='all')

           EmpId                   Name       Salary
count   7.000000                      7     7.000000
unique       NaN                      6          NaN
top          NaN  SRI HARSHAVARDHANAN R          NaN
freq         NaN                      2          NaN
mean    4.000000                    NaN  5714.285714
std     2.160247                    NaN  1603.567451
min     1.000000                    NaN  3000.000000
25%     2.500000                    NaN  5000.000000
50%     4.000000                    NaN  6000.000000
75%     5.500000                    NaN  6500.000000
max     7.000000                    NaN  8000.000000

In [14]:
empCol = df.columns
empCol

Index(['EmpId', 'Name', 'Salary'], dtype='object')

In [15]:
emparray = df.values
emparray

array([[1, 'SREE VARSSINI K S', 5000],
       [2, 'SREEMATHI B', 6000],
       [3, 'SREYA G', 7000],
       [4, 'SREYASKARI MULLAPUDI', 5000],
       [5, 'SRI AKASH U G', 8000],
       [6, 'SRI HARSHAVARDHANAN R', 3000],
       [7, 'SRI HARSHAVARDHANAN R', 6000]], dtype=object)

In [16]:
employee_DF = pd.DataFrame(emparray, columns=empCol)
employee_DF

  EmpId                   Name Salary
0     1      SREE VARSSINI K S   5000
1     2            SREEMATHI B   6000
2     3                SREYA G   7000
3     4   SREYASKARI MULLAPUDI   5000
4     5          SRI AKASH U G   8000
5     6  SRI HARSHAVARDHANAN R   3000
6     7  SRI HARSHAVARDHANAN R   6000